# Generated by Django 5.2.7 on 2025-10-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('report', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
