# Generated by Django 5.2.7 on 2025-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Shoes', 'Shoes'), ('Jersey', 'Jersey'), ('Ball', 'Ball'), ('Pants', 'Pants'), ('Accessories', 'Accessories')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
