# Generated by Django 5.2.7 on 2025-10-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Shoes', 'Shoes'), ('Jersey', 'Jersey'), ('Ball', 'Ball'), ('Hoop', 'Hoop'), ('Accessories', 'Accessories')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, max_length=300, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0-5)', max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]