# Generated by Django 5.2.7 on 2025-10-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_rating_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Jersey', 'Jersey'), ('Ball', 'Ball'), ('Pants', 'Pants'), ('Accessories', 'Accessories')], max_length=50),
        ),
    ]
