# Generated by Django 5.2.7 on 2025-10-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
        ('catalog', '0006_alter_product_category'),
    ]

    operations = [
    ]
