# Generated by Django 5.2.7 on 2025-10-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_merge_20251023_1109'),
        ('catalog', '0007_merge_20251023_1110'),
    ]

    operations = [
    ]
