# Generated by Django 5.2.6 on 2025-10-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_merge_20251023_1109'),
        ('catalog', '0007_merge_20251023_1110'),
        ('catalog', '0007_merge_20251023_2330'),
    ]

    operations = [
    ]
