# Generated by Django 5.2.6 on 2025-10-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_merge_20251023_2348'),
        ('catalog', '0008_merge_20251024_0010'),
    ]

    operations = [
    ]
