# Generated by Django 5.2.7 on 2025-10-22 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('legwear', 'Legwear'), ('jaket', 'Jaket'), ('shoes', 'Shoes'), ('basketball', 'Basketball'), ('equipment', 'Equipment')], default='equipment', max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('tarmak', 'Tarmak'), ('wilson', 'Wilson'), ('spalding', 'Spalding')], default='nike', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
