# Generated by Django 5.2.6 on 2025-10-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_image'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='city',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='full_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='postal_code',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
