# Generated by Django 5.2.6 on 2025-10-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_delete_cart'),
        ('invoice', '0004_alter_invoice_address_alter_invoice_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
    ]
